# Cervical Pose Detection System Configuration

# Detection Thresholds
CERVICAL_FLEXION_THRESHOLD = 0.85
CERVICAL_EXTENSION_THRESHOLD = 1.15
LATERAL_TILT_THRESHOLD = 0.15
NECK_ROTATION_THRESHOLD = 1.5
CHIN_TUCK_THRESHOLD = 0.8

# Calibration Settings
CALIBRATION_FRAMES = 15
CONFIDENCE_SMOOTHING = 0.3

# MediaPipe Settings
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5
MODEL_COMPLEXITY = 1

# Video Settings
DEFAULT_FPS = 15
VIDEO_WIDTH = 640
VIDEO_HEIGHT = 480

# UI Settings
MAX_HISTORY_LENGTH = 10
PERFORMANCE_WINDOW_SIZE = 30
